### PR TITLE
Fix Consent Field

### LINKED ISSUE #1450: Consent field showing up in Core PDF when not checked
**Description**
If a Consent field has a value in the "Description" setting, it will always be considered _not empty_ by Gravity PDF, even if a user didn't check the consent checkbox. This is contrary to how Gravity Forms handles consent fields in the Entry Details page, which always treats unticked Consent fields as empty.

**Step To Reproduce**
1. Add a Consent field to your form and include a value in the "Description" setting.
2. Add a Name field to your form and then save.
3. Setup a Core PDF on the form and ensure the _Show Empty Fields_ option is disabled
4. Submit the form and leave the Consent field unchecked
4. View the PDF

**Expected behavior**
The Consent field would not be shown in the PDF. Currently, it is showing.

**Screenshots**
Screenshot 2023-02-17 at 9 23 16 am

### PR DESCRIPTION
**Pull request by jestonihpi**
## Description
If the consent field is empty, it should not display on PDF, just like GravityForms handling empty consent field. We have added a new filter that allows users to bypass it manually.

Note: Missing Unit tests

#1450 
## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation / docblocks.

### CODE REVIEW

File: src/Helper/Fields/Field_Consent.php [hunk 1]
```diff
@@ -143,4 +139,20 @@ protected function get_non_consent_markup() {
...
+
+	/**
+	 * Add new filter gfpdf_hide_consent_field_if_empty that allows users to manually show consent field if empty on the pdf.
+	 *
+	 * @return string
+	 *
+	 * @since 6.5.4
+	 */
+	public function is_empty() {
+		if ( apply_filters( 'gfpdf_hide_consent_field_if_empty', true, $this->field, $this->entry, $this->form ) ) {
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: This should be `false` by default.

File: src/Helper/Fields/Field_Consent.php [hunk 2]
```diff
@@ -143,4 +139,20 @@ protected function get_non_consent_markup() {
...
+			$value = $this->value();
+			return empty( $value['value'] ); /* hide if empty */
+		}
+
+		return '';
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: This should return `false`

File: src/Helper/Fields/Field_Consent.php [hunk 3]
```diff
@@ -143,4 +139,20 @@ protected function get_non_consent_markup() {
 			__( 'Consent not given.', 'gravity-forms-pdf-extended' )
 		);
 	}
+
+	/**
+	 * Add new filter gfpdf_hide_consent_field_if_empty that allows users to manually show consent field if empty on the pdf.
+	 *
+	 * @return string
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: `@return bool`

File: src/Helper/Fields/Field_Consent.php [hunk 4]
```diff
@@ -143,4 +139,20 @@ protected function get_non_consent_markup() {
 			__( 'Consent not given.', 'gravity-forms-pdf-extended' )
 		);
 	}
+
+	/**
+	 * Add new filter gfpdf_hide_consent_field_if_empty that allows users to manually show consent field if empty on the pdf.
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: Change to "Check if the field is empty"

File: src/Helper/Fields/Field_Consent.php [hunk 5]
```diff
@@ -61,17 +61,13 @@ public function __construct( $field, $entry, Helper_Abstract_Form $gform, Helper
...
-		/* Return empty string if consent field is unticked. */
-		if ( empty( $value['value'] ) ) {
+		$value       = $this->value();
+		$has_consent = $value['value'];
+		if ( $this->is_empty() ) {
 			return '';
 		}
 
-		$markup = $has_consent ? $this->get_consented_markup( $value['label'] ): $this->get_non_consent_markup();
+		$markup      = $has_consent ? $this->get_consented_markup( $value['label'] ) : $this->get_non_consent_markup();
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: Remove these changes

File: src/Helper/Fields/Field_Consent.php [hunk 6]
```diff
@@ -61,17 +61,13 @@ public function __construct( $field, $entry, Helper_Abstract_Form $gform, Helper
...
-		global $gfpdf;
-		$value = $this->value();
-		$has_consent = false;
-		$input = $gfpdf;
-
-		/* Return empty string if consent field is unticked. */
-		if ( empty( $value['value'] ) ) {
+		$value       = $this->value();
+		$has_consent = $value['value'];
+		if ( $this->is_empty() ) {
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Consent.php]: I don't think you need to include these changes here. The field should be filtered out automatically at https://github.com/GravityPDF/gravity-pdf/blob/development/src/View/View_PDF.php#L484

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
@jestonihpi feedback added
