### PR TITLE
Fix undefined currency number fields on Repeater

### LINKED ISSUE #1350: Repeater Notice: Undefined index: currency
**Description**
When a native Repeater field includes a Number field, the following error is generated due to the Repeater Entry we generate not including the `currency` data.

```
PHP Notice: Undefined index: currency in /Users/jakejackson/Sites/payroll/wp-content/plugins/gravity-forms-pdf-extended/src/Helper/Fields/Field_Number.php on line 81
```

### PR DESCRIPTION
**Pull request by jestonihpi**
## Description
Fix the issue when the repeater fields contains a number, by preloading the $entry object with its standard structure.

## Testing instructions

Create a repeater form and add a number on its field.

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
Missing unit tests

**Comment by jestonihpi** [comment]
Hi @jakejackson1 , unit test has added. Thanks.

File: tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * @group   helper
+ * @group   fields
+ */
+class Test_Field_Repeater extends WP_UnitTestCase {
+
+	/**
+	 * Test the Gravity PDF Repeater field add_entry_meta method
+	 */
+	public function test_repeater_add_entry_meta_method() {
+		$form  = json_decode( trim( file_get_contents( dirname( __FILE__ ) . '/../../json/repeater-consent-form.json' ) ), true );
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php]: Let's handle the importing in the bootstrap file like the other PR.

File: tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+		$entry = json_decode( trim( file_get_contents( dirname( __FILE__ ) . '/../../json/repeater-consent-entry.json' ) ), true );
+
+		$form_id          = GFAPI::add_form( $form );
+		$entry['form_id'] = $form_id;
+		$entry_id         = GFAPI::add_entry( $entry );
+		$form_data        = GPDFAPI::get_form_data( $entry_id );
+
+		$repeater = new Field_Repeater( new \GF_Field_Repeater( $form["fields"][1] ), GFAPI::get_entry( $entry_id ), GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );
+		$items    = $repeater->add_entry_meta( $form_data['repeater'][999][0][15] );
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php]: This is a bad unit test. For example, you don't know what the structure of `$form_data['repeater'][999][0][15]` is and you cannot verify the `add_entry_meta()` does what it is meant to do. Further, you aren't testing the value of the array keys to ensure the array replace goes as expected. 

The concern is the `array_replace` overrides the wrong array keys and returns the wrong data, and this is where well-written tests verify the functionality.

Along with passing in different data to `add_entry_meta`, different `$entry` objects should be tested as well.

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
The PR description needs to be updated and have the PR template accurately filled out.

File: src/Helper/Fields/Field_Repeater.php [hunk 3]
```diff
@@ -218,19 +218,39 @@ public function get_repeater_html( $value, $field ) {
...
 
 	/**
-	 * Allow the Repeater fields to act as an entry by padding the entry ID and form ID
+	 * Allow the Repeater fields to act as an entry by padding the needed values for entry.
 	 *
 	 * @param array $item
 	 *
 	 * @return array
 	 *
 	 * @since 5.1
```
Comment (jakejackson1) [inline src/Helper/Fields/Field_Repeater.php]: As this is an entirely new method, the @since tag needs updating.

File: tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+		$entry = $GLOBALS['GFPDF_Test']->entries['repeater-consent-form'][0];
+
+		$form_id          = GFAPI::add_form( $form );
+		$entry['form_id'] = $form_id;
+		$entry_id         = GFAPI::add_entry( $entry );
+
+		$repeater = new Field_Repeater( new \GF_Field_Repeater( $form['fields'][1] ), GFAPI::get_entry( $entry_id ), GPDFAPI::get_form_class(), GPDFAPI::get_misc_class() );
+		$items = $repeater->add_entry_meta( [ 'field_sample_1' => 1, 'field_sample_2' => 2, 'created_by' => 'tester', 'source_url' => 'test.com' ] );
+
+		$this->assertEquals( 1, $items['field_sample_1']);
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php]: Use `assertSame()` so the type is also checked

File: tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+		$this->assertEquals( 'tester', $items['created_by']);
+		$this->assertEquals( 'test.com', $items['source_url']);
+		// make sure that add_entry_meta returns an array with the expected order.
+		$this->assertEquals( 'field_sample_2', key(array_slice($items, -1, 1, true)) );
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/Helper/Fields/Test_Field_Repeater.php]: Running `$items` through `array_values()` and assigning to a new variable, then doing multiple assertions to ensure the order is correctly would be clearer than this one-liner.

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
@jestonihpi almost there.

**Comment by jestonihpi** [comment]
Hi @jakejackson1 . Kindly review these changes : https://github.com/GravityPDF/gravity-pdf/pull/1355/commits/2305211414e772e2270721af17cfa5a3508ec746. Thank you.

**Review by jakejackson1 — APPROVED** [review]
@jestonihpi much better with those unit tests. The code looks good to me. Approved.

When I have time I will do a final real-world check on it.
