### PR TITLE
Process Background Image merge tag 

### LINKED ISSUE #1406: Merge Tags stripped from Background Image setting instead of processing
**Description**
When using the [Background Image feature](https://docs.gravitypdf.com/v6/users/setup-pdf#background-image) with a merge tag in the value, it is [automatically stripped out when output](https://github.com/GravityPDF/gravity-pdf/blob/development/src/View/html/PDF/core_template_styles.php#L69) in the PDF via `esc_raw_url()`.

**Step To Reproduce**
1. Setup a Core PDF on the form
2. In the Background Image setting insert a URL to an image in the media library
3. Add a merge tag to the image URL
4. View the PDF and append URL with `?html=1`
5. View the page source and see the merge tag was not correctly converted to the associated value

**Expected behavior**
Merge tags should be processed correctly. Because we need to escape on output, [merge tags should be pre-processed for this particular field setting](https://github.com/GravityPDF/gravity-pdf/blob/development/src/View/html/PDF/core_template_styles.php#L35).

### PR DESCRIPTION
**Pull request by jestonihpi**
## Description
This PR should solve the issue #1406. 

- I have added `$form` and `$entry` to  View_PDF's  `load_core_template_styles` method. This will enable us to use `process_tags`. 
- Added an `if` statement that checks if the background-image value contains an merge tag before proceeding.

#1406 
## Testing instructions

- Setup a Core PDF on the form
- In the Background Image setting insert a URL to an image in the media library
- Add a merge tag to the image URL
- View the PDF and append URL with ?html=1
- View the page source and see the merge tag was not correctly converted to the associated value

## Checklist:
- [x] I've tested the code.
- [x] My code is easy to read, follow, and understand
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Comment by jestonihpi** [comment]
Hi @jakejackson1 , this pr is now ready for  review. Thank you.

File: src/View/html/PDF/core_template_styles.php [hunk 1]
```diff
@@ -31,8 +33,9 @@
 $first_header = $settings['first_header'] ?? '';
 $first_footer = $settings['first_footer'] ?? '';
 
-$background_color      = $settings['background_color'] ?? '#FFF';
-$background_image      = $settings['background_image'] ?? '';
+$background_color = $settings['background_color'] ?? '#FFF';
+/* Process merge tags if any. */
```
Comment (jakejackson1) [inline src/View/html/PDF/core_template_styles.php]: @jestonihpi let's remove this line

File: src/View/View_PDF.php [hunk 2]
```diff
@@ -631,8 +631,16 @@ public function get_core_template_styles( $settings, $entry ) {
 	 *
 	 * @since 4.0
 	 */
-	public function load_core_template_styles( $settings ) {
-		return $this->load( 'core_template_styles', [ 'settings' => $settings ], false );
+	public function load_core_template_styles( $settings, $form, $entry ) {
```
Comment (jakejackson1) [inline src/View/View_PDF.php]: For backwards compatibility, let's make $form and $entry optional parameters and set to an empty array by default. This will prevent any backwards compatible issues for any one directly using this method.

File: tests/phpunit/unit-tests/test-pdf.php [hunk 3]
```diff
@@ -408,7 +408,7 @@ public function test_multisite_signed_url_access() {
 
 		/* Setup some test data */
 		$_SERVER['HTTP_HOST'] = str_replace( [ 'http://', 'http://' ], '', home_url() );
-		
+
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/test-pdf.php]: Revert the change to this line

File: tests/phpunit/unit-tests/test-pdf.php [hunk 4]
```diff
@@ -1903,7 +1903,7 @@ public function test_core_template_options() {
 		$this->assertNotFalse( strpos( $results, 'This is the footer' ) );
 		$this->assertNotFalse( strpos( $results, 'This is the first footer' ) );
 
-		$this->assertNotFalse( strpos( $results, 'background-image: url(/path/image.png) no-repeat 0 0;' ) );
+		$this->assertNotFalse( strpos( $results, 'background-image: url(/path/image.png?' . $data['entry'][16] . ') no-repeat 0 0;' ) );
```
Comment (jakejackson1) [inline tests/phpunit/unit-tests/test-pdf.php]: Let's hardcode the output of `$data['entry'][16]` rather than make it dynamic. This ensures no unexpected changes to our model.

**Review by jakejackson1 — CHANGES_REQUESTED** [review]
@jestonihpi looking pretty good. Just a few minor changes.

**Comment by jestonihpi** [comment]
Thanks for the feedback @jakejackson1, added this on my today's list.

**Comment by jestonihpi** [comment]
I have applied the requested changes @jakejackson1 , kindly review this pr please.
